version: 0.0
os: linux
files:
    - source: .
      destination: /var/www/wordpress/

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
      
  AfterInstall:
    - location: scripts/permission.sh
      timeout: 300
      runas: root
      
      
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: root
      
